language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
  - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.17.3-Linux-x86_64 cmake-install
  - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  - sudo apt-get install swig
  - sudo apt-get install unrar
  - pip3 install -r requirements.txt
  - sudo apt-get install libsdl1.2-dev libsdl-gfx1.2-dev libsdl-image1.2-dev
  - git clone https://github.com/mgbellemare/Arcade-Learning-Environment.git
  - cd Arcade-Learning-Environment
  - mkdir build && cd build
  - cmake -DUSE_SDL=ON -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=ON ..
  - make -j 4
  - cd ..
  - pip3 install .
  - cd ..

script:
  - python3 AutoROM/smoke_test.py -i