[build-system]
requires = [
    "farama_notifications",
    "setuptools",
    "wheel",
    "requests",
    "tqdm",
    "libtorrent; sys_platform == 'linux'",
    "click",
    "importlib-resources; python_version < '3.9'"
]
